version : "1"

services:
  app :
    build: .
    ports:
      - "8084:9090"
    depends_on:
      - db
#      - redis
#      - rabbit_mq

  db :
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"

#  redis :
#    image : redis
#    ports:
#
#  rabbit_mq :
#    image: rabbitmq





